<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_1" Id="{105f3ca5-a6d7-4d1f-994a-44dc5c5b136d}" SpecialFunc="None">
    <Declaration><![CDATA[//add
FUNCTION_BLOCK FB_1
VAR_INPUT
	nIn1:		INT;
	nIn2:		INT;
END_VAR
VAR_OUTPUT
	nOut1:		INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nOut1:=nIn1+nIn2;
]]></ST>
    </Implementation>
    <LineIds Name="FB_1">
      <LineId Id="9" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>